# Python-In-The-Lab_Project

LOG:

Ripristinato corretto funz branch